"""Base parser interface for platform-specific JD extraction."""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field


@dataclass
class CrawlConfig:
    """Per-platform crawl configuration hints.

    These are translated into ``CrawlerRunConfig`` parameters by the scraper.
    """

    # JavaScript to execute before scraping (e.g. clicking "더보기" buttons)
    js_code: list[str] = field(default_factory=list)
    # Seconds to wait after JS execution for content to load
    js_wait: float = 2.0
    # CSS selector to scope content extraction (None = full page)
    css_selector: str | None = None
    # Tags to exclude from markdown generation
    excluded_tags: list[str] = field(
        default_factory=lambda: ["nav", "footer", "header", "aside", "script", "style", "noscript"],
    )
    # Wait strategy: "domcontentloaded" is faster, "networkidle" waits longer
    wait_until: str = "domcontentloaded"
    # Page timeout in ms
    page_timeout: int = 60000


class BaseParser(ABC):
    """Abstract base class for per-platform JD parsers."""

    @abstractmethod
    def can_handle(self, url: str) -> bool:
        """Return True if this parser supports the given URL."""
        ...

    def get_crawl_config(self) -> CrawlConfig:
        """Return platform-specific crawl configuration.

        Override in subclasses to provide JS execution, CSS targeting, etc.
        """
        return CrawlConfig()

    @abstractmethod
    def parse(self, raw_html: str, crawl_markdown: str, url: str, **kwargs) -> str | dict:
        """Extract JD content from crawled page.

        Args:
            raw_html: The full rendered HTML of the page.
            crawl_markdown: Markdown auto-generated by crawl4ai.
            url: The original URL being scraped.

        Returns:
            Cleaned JD as string or structured dict.
        """
        ...
